module.exports = {
  // ...
  resolve: {
    // ...
    alias: {
      // ...
      'react-dom@^18.2.0': 'react-dom/profiling',
      'schedule/tracking': 'schedule/tracking-profiling',
    },
    // ...
  },
  // ...
};